import React from 'react';
import { ShieldCheck, Info, Zap, Layers, TrendingUp } from 'lucide-react';
import { processSolarData } from '../utils/solarApi';

export default function MeasurementDisplay({ areaSqFt, solarData }) {
    // Process Solar API data
    const solarMeasurements = solarData ? processSolarData(solarData) : null;

    // Pitch multipliers (Intuitive for non-technical users)
    const pitches = [
        { label: 'Flat Roof (Walking Surface)', value: 1.00 },
        { label: 'Low Slope (Slight Incline)', value: 1.05 },
        { label: 'Standard House (Typical)', value: 1.12 },
        { label: 'Steep (Difficult to Walk)', value: 1.25 },
        { label: 'Very Steep (Professional Only)', value: 1.40 },
    ];

    const [multiplier, setMultiplier] = React.useState(1.12); // Default to Standard House
    const [wasteFactor, setWasteFactor] = React.useState(0); // Set to 0% as requested
    const [hasSaved, setHasSaved] = React.useState(false);

    // Sync with Solar API data if the user chooses to
    const handleSyncSolar = React.useCallback(() => {
        if (!solarMeasurements) return;

        // Find closest multiplier to degrees
        const degrees = solarMeasurements.predominantPitchDegrees || 0;
        // Simple mapping: 0-5: Flat, 5-15: Low, 15-30: Standard, 30-45: Steep, 45+: Very Steep
        let newMult = 1.12;
        if (degrees < 5) newMult = 1.00;
        else if (degrees < 15) newMult = 1.05;
        else if (degrees < 30) newMult = 1.12;
        else if (degrees < 45) newMult = 1.25;
        else newMult = 1.40;

        setMultiplier(newMult);
    }, [solarMeasurements]);

    // Automatically sync when measurements become available
    React.useEffect(() => {
        if (solarMeasurements) {
            handleSyncSolar();
        }
    }, [solarMeasurements, handleSyncSolar]);

    if (areaSqFt === null || areaSqFt === 0) return null;

    const pitchAdjustedArea = areaSqFt * multiplier;
    const finalArea = pitchAdjustedArea * (1 + wasteFactor / 100);

    const handleSave = () => {
        const report = `
ROOF MEASUREMENT REPORT
-----------------------
Estimated Area: ${Math.round(finalArea).toLocaleString()} sq ft
Base Area: ${Math.round(areaSqFt).toLocaleString()} sq ft
Pitch Multiplier: x${multiplier}
Waste Factor: ${wasteFactor}%
${solarMeasurements ? `
LiDAR VERIFIED DATA
-------------------
Roof Facets: ${solarMeasurements.facetCount}
Predominant Pitch: ${solarMeasurements.predominantPitchDegrees}° (${solarMeasurements.predominantPitchRatio})
LiDAR Total Area: ${solarMeasurements.totalAreaSqFt.toLocaleString()} sq ft
` : ''}
-----------------------
Generated by Roof Measuring App
        `.trim();

        const blob = new Blob([report], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `roof-measurement-${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        setHasSaved(true);
    };

    return (
        <div className="w-full bg-brand-beige border-t border-brand-navy/10 shadow-[0_-10px_25px_-5px_rgba(26,26,46,0.1)] p-8 z-[1000]">
            <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-12">

                {/* Total Area Display */}
                <div className="text-center md:text-left flex flex-col gap-6 relative">
                    {solarMeasurements && (
                        <div className="absolute -top-12 left-0 flex items-center gap-2 bg-brand-green-dark/10 text-brand-green-dark px-3 py-1.5 rounded-full border border-brand-green-dark/20 animate-in fade-in slide-in-from-bottom-2 duration-700">
                            <ShieldCheck className="w-4 h-4" />
                            <span className="text-[10px] font-mono font-bold uppercase tracking-wider">LiDAR Verified Data Available</span>
                        </div>
                    )}

                    <div>
                        <p className="text-brand-navy/40 text-[10px] uppercase tracking-[0.2em] font-mono font-bold mb-2">Estimated Roof Area</p>
                        <div className="flex items-baseline gap-3">
                            <span className="text-6xl font-serif font-black text-brand-navy tracking-tight">{Math.round(finalArea).toLocaleString()}</span>
                            <span className="text-lg text-brand-navy/60 font-mono font-bold uppercase tracking-widest">sq ft</span>
                        </div>
                    </div>

                    <div className="flex flex-col md:flex-row gap-4">
                        <button
                            onClick={handleSave}
                            className="bg-brand-gold hover:bg-[#B69123] text-brand-navy font-bold py-3.5 px-8 rounded-full shadow-lg transition-all active:scale-95 flex items-center justify-center gap-2 text-sm w-full md:w-fit"
                        >
                            Save Configuration
                        </button>
                        {hasSaved && (
                            <button
                                onClick={() => alert('Proceeding to detailed estimate...')}
                                className="bg-brand-green-dark hover:bg-[#14492E] text-white font-bold py-3.5 px-8 rounded-full shadow-lg transition-all active:scale-95 flex items-center justify-center gap-2 text-sm w-full md:w-fit animate-in fade-in slide-in-from-left-4 duration-500"
                            >
                                Proceed to Estimate
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14" /><path d="m12 5 7 7-7 7" /></svg>
                            </button>
                        )}
                    </div>
                </div>

                {/* Controls */}
                <div className="flex flex-col gap-8">
                    <div className="flex flex-col md:flex-row gap-10 w-full md:w-auto">
                        {/* Pitch Control */}
                        <div className="flex flex-col gap-3 min-w-[260px]">
                            <div className="flex justify-between items-center px-1">
                                <label htmlFor="pitch-select" className="text-[10px] text-brand-navy/40 font-bold uppercase tracking-[0.1em] font-mono">Roof Steepness</label>
                                <span className="text-[10px] font-mono font-bold text-brand-gold bg-brand-gold/10 px-2.5 py-1 rounded-full uppercase tracking-tighter">Multiplier: x{multiplier}</span>
                            </div>
                            <select
                                id="pitch-select"
                                value={multiplier}
                                onChange={(e) => setMultiplier(parseFloat(e.target.value))}
                                className="w-full bg-white border border-brand-navy/10 text-brand-navy text-sm rounded-xl focus:ring-2 focus:ring-brand-gold focus:border-brand-gold block p-3.5 outline-none transition-all hover:border-brand-gold/50 font-bold shadow-sm"
                            >
                                {pitches.map((p) => (
                                    <option key={p.label} value={p.value}>
                                        {p.label}
                                    </option>
                                ))}
                            </select>
                        </div>

                        {/* Waste Factor Control - HIDDEN PER USER REQUEST */}
                        <div className="hidden">
                            <div className="flex justify-between items-center px-1">
                                <label htmlFor="waste-slider" className="text-[10px] text-brand-navy/40 font-bold uppercase tracking-[0.1em] font-mono">Cut & Waste</label>
                                <span className="text-[10px] font-mono font-black text-brand-green-dark bg-brand-green-light px-2.5 py-1 rounded-full">{wasteFactor}% EXTRA</span>
                            </div>
                            <div className="relative pt-2">
                                <input
                                    id="waste-slider"
                                    type="range"
                                    min="0"
                                    max="20"
                                    step="1"
                                    value={wasteFactor}
                                    onChange={(e) => setWasteFactor(parseInt(e.target.value))}
                                    className="w-full h-1.5 bg-brand-navy/5 rounded-full appearance-none cursor-pointer accent-brand-gold"
                                />
                                <div className="flex justify-between text-[10px] text-brand-navy/40 mt-3 px-1 font-mono font-bold uppercase tracking-widest">
                                    <span>Simple</span>
                                    <span className="text-brand-gold">Standard</span>
                                    <span>Complex</span>
                                </div>
                            </div>
                        </div>
                    </div>


                    {/* Professional Measurements from Solar API */}
                    {solarMeasurements && (
                        <div className="mt-4 p-5 bg-white/60 rounded-2xl border border-brand-navy/10 shadow-sm">
                            <div className="flex items-center gap-2 mb-4">
                                <Layers className="w-4 h-4 text-brand-green-dark" />
                                <h3 className="text-xs font-bold text-brand-navy uppercase tracking-wider">Professional Measurements</h3>
                            </div>

                            <div className="grid grid-cols-3 gap-3 mb-4">
                                <div className="text-center p-3 bg-brand-beige/50 rounded-lg">
                                    <div className="text-[10px] text-brand-navy/60 font-mono uppercase mb-1">Roof Facets</div>
                                    <div className="text-xl font-bold text-brand-navy">{solarMeasurements.facetCount}</div>
                                </div>
                                <div className="text-center p-3 bg-brand-beige/50 rounded-lg">
                                    <div className="text-[10px] text-brand-navy/60 font-mono uppercase mb-1">Pitch</div>
                                    <div className="text-xl font-bold text-brand-navy">{solarMeasurements.predominantPitchRatio}</div>
                                    <div className="text-[9px] text-brand-navy/40 font-mono">{solarMeasurements.predominantPitchDegrees}°</div>
                                </div>
                                <div className="text-center p-3 bg-brand-beige/50 rounded-lg">
                                    <div className="text-[10px] text-brand-navy/60 font-mono uppercase mb-1">LiDAR Area</div>
                                    <div className="text-lg font-bold text-brand-navy">{solarMeasurements.totalAreaSqFt.toLocaleString()}</div>
                                    <div className="text-[9px] text-brand-navy/40 font-mono">sq ft</div>
                                </div>
                            </div>

                            <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-[11px]">
                                <div className="flex items-start gap-2">
                                    <Info className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
                                    <div className="text-amber-900">
                                        <strong className="font-bold">Linear measurements unavailable:</strong> Ridge, valley, rake, and eave lengths require premium services.
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
